export const INCREMENT = 'INCREMENT'

export const DELETE_ARTICLE = 'DELETE_ARTICLE'

export const CHANGE_SELECTION = 'CHANGE_SELECTION'

export const CHANGE_DATE_RANGE = 'CHANGE_DATE_RANGE'

export const ADD_COMMENT = 'ADD_COMMENT'

export const LOAD_ALL_ARTICLES = 'LOAD_ALL_ARTICLES'

export const LOAD_ARTICLE = 'LOAD_ARTICLE'

export const ASYNC_START = '_ASYNC_START'

export const ASYNC_SUCCESS = '_ASYNC_SUCCESS'

export const ASYNC_FAIL = '_ASYNC_FAIL'

export const LOAD_ALL_COMMENTS = 'LOAD_ALL_COMMENTS'

export const SHOW_COMMENT_PAGES = 'SHOW_COMMENT_PAGES'

export const COMMENT_PAGES_COUNT = 5

export const LOCAL_LANG_RUS = 'RU'

export const LOCAL_LANG_ENG = 'EN'

