export const localLangRUS = {
  userName: 'Пользователь: ',
  mainMenu: 'Главное меню',
  chngeLng: 'Сменить язык',
  menuCounter: 'Счетчик',
  menuFilters: 'Фильтры',
  menuArticles: 'Статьи',
  menuComments: 'Комментарии',
  menuVirtList: 'Виртуальный список',
  counterButtonTitle: 'Увеличить',
  menuVirtGrid: 'Virtual Grid',
  articleChoose: 'Выберите статью',
  articleButtonTitleClose: 'Закрыть',
  articleButtonTitleOpen: 'Открыть',
  articleButtonTitleDeleteMe: 'Удалить',
  loaderTitle: 'Загрузка...',
  commentButtonTitleShow: 'Показать комментарии',
  commentButtonTitleHide: 'Скрыть комментарии',
  commentButtonAddTitle: 'Добавить',
  commentAddTitle: 'Добавить комментарий',
  commentAddUser: 'Пользователь:',
  commentTextAreaPlaceHolder: 'Введите комментарий...',
  commentNoCommentText: 'Нет комментариев',
  pageTitle: 'Страница',
  pageTotalCommentsTitle: 'Всего комментариев:',
  pageCommentsFromTitle: 'комментарии с ',
  pageCommentsToTitle: ' по '
}

export const localLangENG = {
  userName: 'Uaserame: ',
  mainMenu: 'Main menu',
  chngeLng: 'Change language',
  menuCounter: 'Counter',
  menuFilters: 'Filters',
  menuArticles: 'Articles',
  menuComments: 'Comments',
  menuVirtList: 'Virtual List',
  menuVirtGrid: 'Virtual Grid',
  counterButtonTitle: 'Increase',
  articleChoose: 'Please choose an article',
  articleButtonTitleClose: 'Close',
  articleButtonTitleOpen: 'Open',
  articleButtonTitleDeleteMe: 'Delete me',
  loaderTitle: 'Loading...',
  commentButtonTitleShow: 'Show comments',
  commentButtonTitleHide: 'Hide comments',
  commentButtonAddTitle: 'Add',
  commentAddTitle: 'Add comment',
  commentAddUser: 'User name:',
  commentTextAreaPlaceHolder: 'Put down your comment please...',
  commentNoCommentText: 'No comments yet',
  pageTitle: 'Page',
  pageTotalCommentsTitle: 'Total comments amount:',
  pageCommentsFromTitle: 'comments from ',
  pageCommentsToTitle: ' to '
}

export default { ru: localLangRUS, en: localLangENG }
